from django.urls import path

from . import views

urlpatterns = [
    path('PublicRegister/', views.PublicRegister.as_view()),
    path('DoctorRegister/', views.DoctorRegister.as_view()),
    path('ScientistRegister/', views.ScientistRegister.as_view()),
    path('PublicLogin/', views.PublicLogin.as_view()),
    path('DoctorLogin/', views.DoctorLogin.as_view()),
    path('ScientistLogin/', views.ScientistLogin.as_view()),
    path('getPublicResume/', views.getPublicResume.as_view()),
    path('PublicSaveResume', views.publicSaveResume.as_view()),
    path('getPublicDiagnosisList/', views.getPublicDiagnosisList.as_view()),
    path('PublicEstablishDiagnosis/', views.publicEstablishDiagnosis.as_view()),
    path('PublicLaunchPredict/', views.publicLaunchPridict.as_view()),
    path('getPublicPredictList/', views.getPublicPredictList.as_view()),
    path('getPublicRecommendation/', views.getPublicRecmmendation.as_view()),
    path('getDatasetList/', views.getDatasetList.as_view()),
    path('uploadDataset/', views.uploadDataset.as_view()),
    path('DeleteDataset/', views.DeleteDataset.as_view()),
    path('getModelList/', views.getModelList.as_view()),
    path('getPatientList/', views.getPatientsList.as_view()),
    path('getPatientAssistantTask/', views.getPatientAssistantTask.as_view()),
    path('getBoardList/', views.getBoardsList.as_view()),
    path('uploadModel/', views.uploadModel.as_view()),
    path('deleteModel/', views.deleteModel.as_view()),
    path('getDiagnosisTaskList/', views.getDiagnosisTaskList.as_view()),
    path('DoctorEstablishDiagnosisTask/', views.DoctorEstablishDiagnosisTask.as_view()),
    path('DeleteDiagnosisTask/', views.DeleteDiagnosisTask.as_view()),
    path('updateAssistantNotifyState/', views.updateAssistantNotifyState.as_view()),
    path('getPublicPredictList/', views.getPublicPredictList.as_view()),
    path('DoctorEstablishDiagnosisTask/', views.DoctorEstablishDiagnosisTask.as_view()),
    path('updatePredictState/', views.updatePredictState.as_view()),
    path('getRecommendationTaskList/', views.getRecommendationTaskList.as_view()),
    path('updateScheme', views.updateScheme.as_view()),
    path('updateSchemeState', views.updateSchemeState.as_view()),
    path('establishSchemeTask', views.establishSchemeTask.as_view()),
    path('uploadModel/', views.uploadModel.as_view()),
    path('getModelList/', views.getModelList.as_view()),
    path('deleteModel/', views.deleteModel.as_view()),
    path('getScientistDignosisTaskList/', views.getScientistDignosisTaskList.as_view()),
    path('establishScientistDiagnosisTask/', views.establishScientistDiagnosisTask.as_view()),
    path('DeleteScientistDiagnosisTask/', views.DeleteScientistDiagnosisTask.as_view()),
    path('getScientistPredictTaskList/', views.getScientistPredictTaskList.as_view()),
    path('ScientistEstablishPredictTask/', views.ScientistEstablishPredictTask.as_view()),
    path('getScientistRecommendationTaskList/', views.getScientistRecommendationTaskList.as_view()),
    path('ScientistEstablishSchemeTask/', views.ScientistEstablishSchemeTask.as_view()),
]
