# Generated by Django 5.0.3 on 2024-03-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='数据集编号')),
                ('name', models.CharField(max_length=255, verbose_name='数据集名称')),
                ('ownerID', models.CharField(max_length=50, verbose_name='数据集所有者')),
                ('ownerName', models.CharField(max_length=255, verbose_name='数据集所有者姓名')),
                ('time', models.DateTimeField(verbose_name='数据集上传时间')),
                ('size', models.IntegerField(verbose_name='数据集大小')),
                ('scene', models.CharField(max_length=255, verbose_name='数据集应用场景')),
                ('description', models.TextField(verbose_name='数据集描述')),
                ('data', models.FileField(upload_to='', verbose_name='数据集文件')),
            ],
            options={
                'verbose_name': '数据集信息',
                'db_table': 'data',
                'indexes': [models.Index(fields=['id'], name='data_id_aec06e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='医生账号')),
                ('name', models.CharField(max_length=255, verbose_name='医生姓名')),
                ('password', models.CharField(max_length=255, verbose_name='医生密码')),
                ('hospital', models.CharField(max_length=255, verbose_name='所属医院')),
                ('department', models.CharField(max_length=255, verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '医生信息',
                'db_table': 'doctor',
                'indexes': [models.Index(fields=['id'], name='doctor_id_ecf006_idx')],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='模型编号')),
                ('name', models.CharField(max_length=255, verbose_name='模型名称')),
                ('ownerID', models.CharField(max_length=50, verbose_name='模型所有者')),
                ('ownerName', models.CharField(max_length=255, verbose_name='模型所有者姓名')),
                ('time', models.DateTimeField(verbose_name='模型上传时间')),
                ('scene', models.CharField(max_length=255, verbose_name='模型应用场景')),
                ('data', models.CharField(max_length=255, verbose_name='模型数据集')),
                ('model', models.FileField(upload_to='', verbose_name='模型文件')),
                ('description', models.TextField(verbose_name='模型描述')),
            ],
            options={
                'verbose_name': '模型信息',
                'db_table': 'model',
                'indexes': [models.Index(fields=['id'], name='model_id_2ffab6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户账号')),
                ('name', models.CharField(max_length=255, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('gender', models.CharField(max_length=10, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('region', models.CharField(max_length=255, verbose_name='用户住址')),
                ('education', models.CharField(max_length=255, verbose_name='用户学历')),
                ('phone', models.CharField(max_length=255, verbose_name='用户电话')),
                ('ApoE', models.FloatField(verbose_name='ApoE')),
                ('MMSE', models.FloatField(verbose_name='MMSE')),
                ('CDR_Global', models.FloatField(verbose_name='CDR_Global')),
                ('CDR_SOB', models.FloatField(verbose_name='CDR_SOB')),
                ('ADAS_Cog', models.FloatField(verbose_name='ADAS_Cog')),
                ('MRI', models.FloatField(verbose_name='MRI')),
                ('PET', models.FloatField(verbose_name='PET')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'public',
                'indexes': [models.Index(fields=['id'], name='public_id_0f9404_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='模板编号')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('ownerID', models.CharField(max_length=50, verbose_name='模板所有者')),
                ('ownerName', models.CharField(max_length=255, verbose_name='模板所有者姓名')),
                ('time', models.DateTimeField(verbose_name='模板上传时间')),
                ('scene', models.CharField(max_length=255, verbose_name='模板应用场景')),
                ('description', models.TextField(verbose_name='模板描述')),
                ('data', models.FileField(upload_to='', verbose_name='模板文件')),
            ],
            options={
                'verbose_name': '病例模板',
                'db_table': 'record_template',
                'indexes': [models.Index(fields=['id'], name='record_temp_id_28237d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='研究员账号')),
                ('name', models.CharField(max_length=255, verbose_name='研究员姓名')),
                ('password', models.CharField(max_length=255, verbose_name='研究员密码')),
                ('department', models.CharField(max_length=255, verbose_name='所属单位')),
            ],
            options={
                'verbose_name': '研究员信息',
                'db_table': 'researcher',
                'indexes': [models.Index(fields=['id'], name='researcher_id_32ef2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictMission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('startTime', models.DateField(verbose_name='任务开始时间')),
                ('endTime', models.DateField(verbose_name='任务结束时间')),
                ('risk', models.TextField(verbose_name='风险预测')),
                ('state', models.CharField(max_length=255, verbose_name='任务状态')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.public', verbose_name='患者账号')),
            ],
            options={
                'verbose_name': '预测任务',
                'db_table': 'predict_mission',
                'indexes': [models.Index(fields=['id'], name='predict_mis_id_ecda9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanRecommendMission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('startTime', models.DateField(verbose_name='任务开始时间')),
                ('endTime', models.DateField(verbose_name='任务结束时间')),
                ('plan', models.TextField(verbose_name='干预方案')),
                ('state', models.CharField(max_length=255, verbose_name='任务状态')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.public', verbose_name='患者账号')),
            ],
            options={
                'verbose_name': '干预方案推荐任务',
                'db_table': 'plan_recommend_mission',
                'indexes': [models.Index(fields=['id'], name='plan_recomm_id_6b4db9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('startTime', models.DateField(verbose_name='任务开始时间')),
                ('endTime', models.DateField(verbose_name='任务结束时间')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('result', models.TextField(verbose_name='任务结果')),
                ('state', models.CharField(max_length=255, verbose_name='任务状态')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.public', verbose_name='患者账号')),
            ],
            options={
                'verbose_name': '诊断任务',
                'db_table': 'diagnosis_mission',
                'indexes': [models.Index(fields=['id'], name='diagnosis_m_id_4d9a71_idx')],
            },
        ),
    ]
