# Generated by Django 5.0.3 on 2024-03-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='用户生日'),
        ),
    ]
